basePath: /auth/
definitions:
  errors.ErrorModel:
    properties:
      error: {}
      isSuccess:
        type: boolean
      message:
        type: string
    type: object
  security.SecretKey:
    properties:
      secret_key:
        type: string
    type: object
  struct_test.AdminAcc:
    description: struct for getting the credentials
    properties:
      department:
        type: string
      name:
        type: string
    type: object
  struct_test.Student:
    properties:
      amount:
        type: integer
      department:
        type: string
      id:
        type: integer
      miscellaneous:
        type: string
      name:
        type: string
      payment_method:
        type: integer
      student_id:
        type: integer
    type: object
info:
  contact: {}
  description: UI testing for Payment Method
  title: Finance Web Application
  version: 1.16.2
paths:
  /register/teacher:
    post:
      consumes:
      - application/json
      description: Add a new teacher to the database
      parameters:
      - description: Enter the Description
        in: body
        name: department
        required: true
        schema:
          $ref: '#/definitions/struct_test.AdminAcc'
      produces:
      - application/json
      responses:
        "200":
          description: Teacher added successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.ErrorModel'
      security:
      - JWT-Token: []
      summary: Create a new teacher
      tags:
      - teachers
  /secure/login:
    post:
      description: Auto generate secret key
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully accessed
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.ErrorModel'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.ErrorModel'
      security:
      - JWT-Token: []
      summary: It will generate the key that will use to log-in in swagger
      tags:
      - Admin
  /students:
    post:
      consumes:
      - application/json
      description: Create a new student account with the provided data
      parameters:
      - description: Student data to be created
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/struct_test.Student'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/struct_test.Student'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.ErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.ErrorModel'
      summary: Create a new student account
      tags:
      - Students
securityDefinitions:
  JWT-Token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
